spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password
    driverClassName: org.postgresql.Driver
  liquibase:
    default-schema: public
logging:
  level:
    dev.vanadium.quasarplatform: info